name: ollert

services:
  db:
    image: mariadb:11.8
    restart: "no"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-ollert}
      MYSQL_USER: ${DB_USERNAME:-ollert}
      MYSQL_PASSWORD: ${DB_PASSWORD:-ollert}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-ollert}
    ports:
      - "${DB_PORT:-9937}:3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailpit:
    image: axllent/mailpit
    restart: "no"
    ports:
      - "${MAILPIT_SMTP_PORT:-1025}:1025"
      - "${MAILPIT_UI_PORT:-8025}:8025"
