#!/usr/bin/env bash
# Generates api/.env, web/.env, mcp/.env, e2e/.env, and .kamal/secrets from
# the root .env (copy .env.example -> .env and fill it out first — see
# README.md#local-development).
#
# Usage: bun run env [-f|--force]
# Skips a target file that already exists unless -f/--force is passed.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT_DIR/.env"
FORCE=0

for arg in "$@"; do
  case "$arg" in
    -f|--force) FORCE=1 ;;
    *)
      echo "Unknown argument: $arg (expected -f/--force)" >&2
      exit 1
      ;;
  esac
done

if [[ ! -f "$ENV_FILE" ]]; then
  echo "No .env at repo root. Copy .env.example to .env, fill it out, then re-run." >&2
  exit 1
fi

# Written for bash 3.2 (macOS default /bin/bash) — no associative arrays.
write_target() {
  local prefix="$1" target="$2"
  if [[ -f "$target" && "$FORCE" -eq 0 ]]; then
    echo "Skip (exists): $target"
    return
  fi
  mkdir -p "$(dirname "$target")"
  {
    echo "# Generated by scripts/sync-env.sh from .env at the repo root."
    echo "# Edit .env there and re-run \`bun run env -- --force\` to regenerate."
    grep -E "^${prefix}__[A-Za-z0-9_]+=" "$ENV_FILE" | sed -E "s/^${prefix}__//"
  } > "$target"
  echo "Wrote: $target"
}

write_target API   "$ROOT_DIR/api/.env"
write_target WEB   "$ROOT_DIR/web/.env"
write_target MCP   "$ROOT_DIR/mcp/.env"
write_target E2E   "$ROOT_DIR/e2e/.env"
write_target KAMAL "$ROOT_DIR/.kamal/secrets"
