#!/usr/bin/env bash
# Generates api/.env, web/.env, mcp/.env, e2e/.env, and .kamal/secrets from
# the root .env (copy .env.example -> .env and fill it out first — see
# README.md#local-development).
#
# Usage: bun run env [-f|--force]
# Skips a target file that already exists unless -f/--force is passed.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT_DIR/.env"
FORCE=0

for arg in "$@"; do
  case "$arg" in
    -f|--force) FORCE=1 ;;
    *)
      echo "Unknown argument: $arg (expected -f/--force)" >&2
      exit 1
      ;;
  esac
done

if [[ ! -f "$ENV_FILE" ]]; then
  echo "No .env at repo root. Copy .env.example to .env, fill it out, then re-run." >&2
  exit 1
fi

# Written for bash 3.2 (macOS default /bin/bash) — no associative arrays.

# Echo the value of KEY (a root-.env key, with its prefix) from $ENV_FILE, or
# empty if absent. cut -f2- preserves internal '=' (connection strings carry
# ?ssl=true&ssl_mode=require).
root_value() {
  grep -E "^$1=" "$ENV_FILE" | head -1 | cut -d= -f2-
}

# $1 prefix, $2 target path, $3 optional extra line to append after the
# prefix-stripped block (empty → nothing appended). Honors the skip/--force
# logic for the whole file, including the extra line.
write_target() {
  local prefix="$1" target="$2" extra="${3:-}"
  if [[ -f "$target" && "$FORCE" -eq 0 ]]; then
    echo "Skip (exists): $target"
    return
  fi
  mkdir -p "$(dirname "$target")"
  {
    echo "# Generated by scripts/sync-env.sh from .env at the repo root."
    echo "# Edit .env there and re-run \`bun run env -- --force\` to regenerate."
    { grep -E "^${prefix}__[A-Za-z0-9_]+=" "$ENV_FILE" || :; } | sed -E "s/^${prefix}__//"
    [[ -n "$extra" ]] && printf '%s\n' "$extra"
  } > "$target"
  echo "Wrote: $target"
}

# API also gets DATABASE_URL_PROD from the root KAMAL__DATABASE_URL (the single
# source of truth for the prod connection string) so `bun migrate:prod` can run
# phinx against hosted Supabase via the `prod` Datasources connection. Omitted
# (with a stderr note) when KAMAL__DATABASE_URL is unset — `bun migrate:prod`
# then fails loudly, which is the right signal for a local-only setup.
PROD_URL="$(root_value KAMAL__DATABASE_URL)"
PROD_LINE=""
if [[ -n "$PROD_URL" ]]; then
  PROD_LINE="DATABASE_URL_PROD=${PROD_URL}"
else
  echo "Note: KAMAL__DATABASE_URL empty in .env — DATABASE_URL_PROD omitted; bun migrate:prod unavailable until you fill it." >&2
fi
write_target API   "$ROOT_DIR/api/.env" "$PROD_LINE"
write_target WEB   "$ROOT_DIR/web/.env"
write_target MCP   "$ROOT_DIR/mcp/.env"
write_target E2E   "$ROOT_DIR/e2e/.env"
write_target KAMAL "$ROOT_DIR/.kamal/secrets"
