/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthenticatedBoardsBoardIdRouteImport } from './routes/_authenticated/boards/$boardId'
import { Route as AuthenticatedOrgsIndexRouteImport } from './routes/_authenticated/orgs/index'
import { Route as AuthenticatedOrgsOrgIdIndexRouteImport } from './routes/_authenticated/orgs/$orgId/index'
import { Route as AuthenticatedOrgsOrgIdMembersRouteImport } from './routes/_authenticated/orgs/$orgId/members'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBoardsBoardIdRoute =
  AuthenticatedBoardsBoardIdRouteImport.update({
    id: '/boards/$boardId',
    path: '/boards/$boardId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrgsIndexRoute = AuthenticatedOrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrgsOrgIdIndexRoute =
  AuthenticatedOrgsOrgIdIndexRouteImport.update({
    id: '/orgs/$orgId/',
    path: '/orgs/$orgId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrgsOrgIdMembersRoute =
  AuthenticatedOrgsOrgIdMembersRouteImport.update({
    id: '/orgs/$orgId/members',
    path: '/orgs/$orgId/members',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/boards/$boardId': typeof AuthenticatedBoardsBoardIdRoute
  '/orgs/': typeof AuthenticatedOrgsIndexRoute
  '/orgs/$orgId/members': typeof AuthenticatedOrgsOrgIdMembersRoute
  '/orgs/$orgId/': typeof AuthenticatedOrgsOrgIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/boards/$boardId': typeof AuthenticatedBoardsBoardIdRoute
  '/orgs': typeof AuthenticatedOrgsIndexRoute
  '/orgs/$orgId/members': typeof AuthenticatedOrgsOrgIdMembersRoute
  '/orgs/$orgId': typeof AuthenticatedOrgsOrgIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/boards/$boardId': typeof AuthenticatedBoardsBoardIdRoute
  '/_authenticated/orgs/': typeof AuthenticatedOrgsIndexRoute
  '/_authenticated/orgs/$orgId/members': typeof AuthenticatedOrgsOrgIdMembersRoute
  '/_authenticated/orgs/$orgId/': typeof AuthenticatedOrgsOrgIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/auth/callback'
    | '/boards/$boardId'
    | '/orgs/'
    | '/orgs/$orgId/members'
    | '/orgs/$orgId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/auth/callback'
    | '/boards/$boardId'
    | '/orgs'
    | '/orgs/$orgId/members'
    | '/orgs/$orgId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/auth/callback'
    | '/_authenticated/boards/$boardId'
    | '/_authenticated/orgs/'
    | '/_authenticated/orgs/$orgId/members'
    | '/_authenticated/orgs/$orgId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/boards/$boardId': {
      id: '/_authenticated/boards/$boardId'
      path: '/boards/$boardId'
      fullPath: '/boards/$boardId'
      preLoaderRoute: typeof AuthenticatedBoardsBoardIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orgs/': {
      id: '/_authenticated/orgs/'
      path: '/orgs'
      fullPath: '/orgs/'
      preLoaderRoute: typeof AuthenticatedOrgsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orgs/$orgId/': {
      id: '/_authenticated/orgs/$orgId/'
      path: '/orgs/$orgId'
      fullPath: '/orgs/$orgId/'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orgs/$orgId/members': {
      id: '/_authenticated/orgs/$orgId/members'
      path: '/orgs/$orgId/members'
      fullPath: '/orgs/$orgId/members'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdMembersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBoardsBoardIdRoute: typeof AuthenticatedBoardsBoardIdRoute
  AuthenticatedOrgsIndexRoute: typeof AuthenticatedOrgsIndexRoute
  AuthenticatedOrgsOrgIdMembersRoute: typeof AuthenticatedOrgsOrgIdMembersRoute
  AuthenticatedOrgsOrgIdIndexRoute: typeof AuthenticatedOrgsOrgIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBoardsBoardIdRoute: AuthenticatedBoardsBoardIdRoute,
  AuthenticatedOrgsIndexRoute: AuthenticatedOrgsIndexRoute,
  AuthenticatedOrgsOrgIdMembersRoute: AuthenticatedOrgsOrgIdMembersRoute,
  AuthenticatedOrgsOrgIdIndexRoute: AuthenticatedOrgsOrgIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
